services:
  #App
  bitdata:
    image: bitdata_app
    container_name: bitdata_app
    depends_on:
      - kafka
      - mongodb
      - wallet-mock
    ports:
      - "7070:7070"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
      WALLET_API_BASE_URL: http://wallet-mock:8081

  #Mock wallet API
  wallet-mock:
    build:
      context: ./mock-wallet-service
    container_name: wallet-mock
    ports:
      - "8081:8081"

  #Database
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - "27017:27017"

  #Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server_bitData
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_bitData
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper_bitData
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka_bitData
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  
volumes:
  grafana_data:
    
