spring:
  application:
    name: BitData
  cloud:
    function:
      definition: sendUnconfirmedTransactions;processTransactions;sendAnalyticsToAdvancedProcess;advancedProcess
    stream:
      bindings:
        sendUnconfirmedTransactions-out-0:
          destination: processTransactions
          contentType: application/json

        processTransactions-in-0:
          destination: processTransactions
          contentType: application/json

        sendAnalyticsToAdvancedProcess-out-0:
          destination: advancedProcess
          contentType: application/json

        advancedProcess-in-0:
          destination: advancedProcess
          contentType: application/json

      kafka:
        binder:
          brokers: kafka:9092
          autoCreateTopics: true
  data:
    mongodb:
      uri: mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
  reactor:
    netty:
      metrics:
        enabled: true

server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG
